---
- name: Create backup dir
  file:
    path: /etc/yum.repos.d/backup
    state: directory

- name: Take a backup of all the Rocky repos
  copy:
    src: "{{ item }}"
    dest: "{{ item | dirname }}/backup/backup-{{ item | basename }}"
    remote_src: yes
    force: false
  loop:
    - /etc/yum.repos.d/Rocky-AppStream.repo
    - /etc/yum.repos.d/Rocky-BaseOS.repo
    - /etc/yum.repos.d/Rocky-Debuginfo.repo
    - /etc/yum.repos.d/Rocky-Devel.repo
    - /etc/yum.repos.d/Rocky-Extras.repo
    - /etc/yum.repos.d/Rocky-HighAvailability.repo
    - /etc/yum.repos.d/Rocky-Media.repo
    - /etc/yum.repos.d/Rocky-NFV.repo
    - /etc/yum.repos.d/Rocky-Plus.repo
    - /etc/yum.repos.d/Rocky-PowerTools.repo
    - /etc/yum.repos.d/Rocky-ResilientStorage.repo
    - /etc/yum.repos.d/Rocky-RT.repo
    - /etc/yum.repos.d/Rocky-Sources.repo

- name: Disable the backup repo files
  lineinfile:
    path: "{{ item | dirname }}/backup/backup-{{ item | basename }}"
    regexp: '^enabled='
    line: 'enabled=0'
    backup: no
  loop:
    - /etc/yum.repos.d/Rocky-AppStream.repo
    - /etc/yum.repos.d/Rocky-BaseOS.repo
    - /etc/yum.repos.d/Rocky-Debuginfo.repo
    - /etc/yum.repos.d/Rocky-Devel.repo
    - /etc/yum.repos.d/Rocky-Extras.repo
    - /etc/yum.repos.d/Rocky-HighAvailability.repo
    - /etc/yum.repos.d/Rocky-Media.repo
    - /etc/yum.repos.d/Rocky-NFV.repo
    - /etc/yum.repos.d/Rocky-Plus.repo
    - /etc/yum.repos.d/Rocky-PowerTools.repo
    - /etc/yum.repos.d/Rocky-ResilientStorage.repo
    - /etc/yum.repos.d/Rocky-RT.repo
    - /etc/yum.repos.d/Rocky-Sources.repo

- name: Sync over working repo files
  synchronize:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  loop:
    - Rocky-AppStream.repo
    - Rocky-BaseOS.repo
    - Rocky-Debuginfo.repo
    - Rocky-Devel.repo
    - Rocky-Extras.repo
    - Rocky-HighAvailability.repo
    - Rocky-Media.repo
    - Rocky-NFV.repo
    - Rocky-Plus.repo
    - Rocky-PowerTools.repo
    - Rocky-ResilientStorage.repo
    - Rocky-RT.repo
    - Rocky-Sources.repo

- name: Clean DNF cache
  command: dnf clean all
