---
- hosts: all
  gather_facts: no
  vars_files:
    - vault.yml

  tasks:
    # Tag: manage_element
    - name: Create VideoCopilot directory if not exists (Element)
      file:
        path: "{{ item  }}"
        state: directory
        mode: '0755'
      loop:
       - "/Library/Application Support/VideoCopilot"
      tags: manage_element


    - name: Copy vcutil to client systems (Element)
      copy:
        src: /Users/jayaput/Documents/ansible/MAC/vc/vcutil/vcinstallutil
        dest: /var/tmp/vcinstallutil
        mode: '0755'
      tags: manage_element

    - name: Run vcinstallutil to install Element license
      command: ./vcinstallutil license install {{ email_id }} {{ email_pass }} elementv2
      args:
        chdir: /var/tmp
      become: yes
      tags: manage_element


    - name: Copy vcutil to client systems (Optical Flares)
      copy:
        src:  /Users/jayaput/Documents/ansible/MAC/vc/vcutil/vcinstallutil
        dest: /var/tmp/vcinstallutil
        mode: '0755'
      tags: manage_optical

    - name: Run vcinstallutil to install Optical Flares license
      command: ./vcinstallutil license install {{ email_id }} {{ email_pass }} opticalflares
      args:
        chdir: /var/tmp
      become: yes
      tags: manage_optical

    # Tag: manage_license_removal
    - name: Remove Element license
      file:
        path: /Library/Application Support/VideoCopilot/element2_license
        state: absent
      tags: manage_license_removal

    - name: Remove Optical Flares license
      file:
        path: /Library/Application Support/VideoCopilot/optical_flares
        state: absent
      tags: manage_license_removal

