---
- hosts: all
  gather_facts: no
  vars_files:
    - vault.yml  # Contains sensitive variables if needed

  vars:
    ae_versions: ["2023", "2024", "2025"]  # List potential After Effects versions

  tasks:
    - name: Check for installed Adobe After Effects versions
      become: yes
      become_user: root
      become_method: su
      stat:
        path: "/Applications/Adobe After Effects {{ item }}/Plug-ins/"
      loop: "{{ ae_versions }}"
      register: ae_check

    - name: Collect installed Adobe After Effects versions
      set_fact:
        installed_versions: "{{ installed_versions | default([]) + [item.item] }}"
      loop: "{{ ae_check.results }}"
      when: item.stat.exists

    - name: Display summary of installed Adobe After Effects versions
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Installed Adobe After Effects versions: {{ installed_versions | default('None') }}

