---
- hosts: all
  gather_facts: no
  vars_files:
    - vault.yml
  tasks:
    - name: Copy plugin files to Adobe After Effects Plug-ins folder
      become: yes
      become_user: root
      become_method: su
      copy:
        src: /Users/jayaput/Documents/ansible/MAC/plugin_network/
        dest: /Applications/Adobe After Effects 2025/Plug-ins/
        owner: wltadmin
        group: everyone
        mode: '777'
        remote_src: no  # Since the source is now on the local machine

    - name: Change permissions of .plugin files
      become: yes
      become_user: root
      become_method: su
      shell: chmod -R 777 /Applications/Adobe\ After\ Effects\ 2025/Plug-ins/*.plugin

    - name: Remove aescriptsLicensingServer.plist if it exists
      become: yes
      become_user: root
      become_method: su
      file:
       path: "/Library/Application Support/aescripts/aescriptsLicensingServer.plist"
       state: absent
      ignore_errors: yes
      tags:
       - license

    - name: Get list of users excluding specific users
      shell: "ls /Users | grep -Ev 'shared|wltadmin|wltsupport|.localized|Shared'"
      register: user_list
      tags: 
       - license_user
   
    - name: Remove user-specific aescriptsLicensingServer.plist for each user if it exists
      file:
        path: "/Users/{{ item }}/Library/Application Support/aescripts/aescriptsLicensingServer.plist"
        state: absent
      loop: "{{ user_list.stdout_lines }}"
      ignore_errors: yes
      tags:
        - license_user

    - name: Copy network license tool to /var/tmp
      become: yes
      become_user: root
      become_method: su
      copy:
        src: /Users/jayaput/Documents/ansible/MAC/network_lic_tool/aescriptsLicenseServerTool
        dest: /var/tmp/aescriptsLicenseServerTool
        owner: root
        group: admin
        mode: '0755'
        remote_src: no  # Local source path
      tags:
        - license


    - name: Run the license server tool
      become: yes
      become_user: root
      become_method: su
#      command: /var/tmp/aescriptsLicenseServerTool 172.27.93.117:27500
      command: /var/tmp/aescriptsLicenseServerTool 172.24.146.100:27100
      register: license_output
      tags:
        - license


    - name: Print the license tool output
      debug:
        msg: "{{ license_output.stdout }}"
      tags:
       - license

