---
- name: add hosts entry 
  hosts: linux
  remote_user: root
  gather_facts: false
  become: yes
  tasks:
    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
       path: /etc/hosts
       line: 172.24.150.45  wl22smtco01.ind.emea.williamslea.grp
       create: yes
    - name: mount all
      command: mount -a
      become: true
