---
- hosts: assist04.dyn.smoke.lon
  roles:
    - role: smoke-repo
      vars:
        do: link
    - role: blackmagic-desktopvideo
      vars:
        do: install
        desktopvideo_version: 14.0.1a2
    - role: smoke-repo
      vars:
        do: unlink
