- name: Check services after reboot
  hosts: all
  become: yes
  tasks:
    - name: Wait for the system to come back online
      wait_for:
        timeout: 10
        state: started
        delay: 5

    - name: Check if all services are up after reboot
      command: systemctl list-units --type=service --state=running
      register: post_reboot_service_status

    - name: Display services after reboot
      debug:
        msg: "{{ post_reboot_service_status.stdout_lines }}"

