---
- name: Check license status
  hosts: license
  remote_user: root
  gather_facts: no
  become: yes
  tasks:
    - name: Check Genarts license
      shell: "/usr/borisfx/rlm/rlmutil rlmstat -a -c /usr/borisfx/rlm/*.lic | grep -i inuse"
      register: genarts_license_output
    - debug:
        var: genarts_license_output.stdout_lines

    - name: Check Neat Video license
      shell: "/opt/neatvideo/rlmutil rlmstat -a | grep -i inuse"
      register: neat_video_license_output
    - debug:
        var: neat_video_license_output.stdout_lines


    - name: Print Houdini license status
      shell: "/usr/lib/sesi/sesictrl print-license"
      register: houdini_license_output
    - debug:
        var: houdini_license_output.stdout_lines

    - name: Check adsk Arnold license
      shell: "/opt/flexnetserver/lmutil lmstat -a -c /opt/flexnetserver/adsk_server.lic | grep use"
      register: adsk_arnold_license_output
    - debug:
        var: adsk_arnold_license_output.stdout_lines

    - name: Check aescripts-License-Server service status
      shell: "systemctl status aescripts-License-Server.service | grep 'Active:'"
      register: aescripts_license_server_output
    - debug:
        var: aescripts_license_server_output.stdout_lines

    - name: Check Chaos web page
      shell: "systemctl status vrlservice.service | grep 'Active:'"
      register: chaos
    - debug:
        var: chaos.stdout_lines

